export const ANDB_ORCHESTRATOR = 'ANDB_ORCHESTRATOR';
export const STORAGE_SERVICE = 'STORAGE_SERVICE';
export const PROJECT_CONFIG_SERVICE = 'PROJECT_CONFIG_SERVICE';
export const EXPORTER_SERVICE = 'EXPORTER_SERVICE';
export const COMPARATOR_SERVICE = 'COMPARATOR_SERVICE';
export const MIGRATOR_SERVICE = 'MIGRATOR_SERVICE';
export const DRIVER_FACTORY_SERVICE = 'DRIVER_FACTORY_SERVICE';
export const REPORTER_SERVICE = 'REPORTER_SERVICE';
